version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: land_registry_db
    restart: always
    environment:
      POSTGRES_USER: landregistry
      POSTGRES_PASSWORD: landregistry
      POSTGRES_DB: land_registry
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: land_registry_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
